### ISSUE TITLE
Problem restoring divider position

### ISSUE THREAD

**Issue by iXo** [andrewauclair/ModernDocking#66]
Hi,

I have difficulties to restore the divider position of a 3 column application.

I am using the window layout builder, my main dockable id is the one in the middle, I have a component to it's left, and 2 components to it's right but a tabbed group.

During the layout building I force the divider position to 0.11 for the left part, and 0.88 to the right part. It is displayed correctly.

If I move the right divider somewhere else (it is persisted as 0.50), and when I launch the application again, I can see the divider going to the saved value (0.50), then just after being forced back to it's original value : 0.80

If I move one of the panel that is on the group to underneath the left panel, the restoration is doing what's is expected, and is restored where I put it, and the horizontal divider that have been persisted is restored correctly, but maybe it's because this position is not described in the original layout.

**Comment by andrewauclair** [comment]
Hi, thanks for writing an issue. Could you possibly supply some screenshots? I think I know what you're referring to, but it's easier to see it. The divider repositioning is a bit tricky. The divider position cannot be set until the divider is actually visible on the screen (otherwise the call does nothing). That's why you'll see them start at one spot and quickly reposition. They're also nested panels and I believe the outer/inner divider position can influence the other.

**Comment by iXo** [comment]
Sure ! I would to help

![image](https://github.com/andrewauclair/ModernDocking/assets/401900/d775d2ee-2536-4075-8c67-5e3fa6667bf4)
This screenshot is the first start of the app with the persistence file deleted. As you can see the column on the right is small in width.

![image](https://github.com/andrewauclair/ModernDocking/assets/401900/c7fa614c-cbe9-4fb3-8fcd-0981fd5c56bc)
Here I change the divider position, to be around 50%, and indeed in the persistence file it is around 0.5

When I close the app and start it again, the divider goes back to it's original position, but I can see it was restored at 0.5 for a very small duration, then came back to it's original value like on the first screenshot, and the persistence file is indeed updated to be 0.8


![image](https://github.com/andrewauclair/ModernDocking/assets/401900/2ee00615-1d4d-4a23-bf44-4ff430e42cb3)
But as you can see, moving a panel somewhere else, is saved correctly, and restored correctly, I suspect that is because this location and position wasn't in the original layout.

**Comment by andrewauclair** [comment]
Thanks! I believe I was able to improve this. Nested JSplitPanes are very tricky. It turns out that the divider positions need to be restored started with the deepest nested JSplitPane and working your way out. If you work from the top down then you run into issues with the position changing due to resize weights.

**Comment by iXo** [comment]
This works perfectly. Thanks for all.

**Comment by andrewauclair** [comment]
Your panels could have minimum sizes that are changing it I guess.

**Comment by andrewauclair** [comment]
@iXo I just spent several hours looking at this again. Turns out there was indeed still an issue to be fixed. Restoring the splits starting with the deepest was not the solution. I had to restore the outermost split first, wait for it to be completely displayed and then move to the next one. This should now restore splits to the exact same position they were at in the layout.

**Comment by iXo** [comment]
Yes !! Congratulation for your amazing job, and thanks, indeed I totally see the difference and it works as expected for restoring the saved position ! I was searching everywhere where I had some calls to setSize(...) without any luck so far. But now the mmi is displayed exactly like when we closed it. It's funny to see it moved itself.

Thanks !

**Comment by andrewauclair** [comment]
Excellent! That was a pain but a nice puzzle to solve.
